# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangohaystack', '0002_note_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='fileUpload',
            field=models.FileField(upload_to=''),
        ),
    ]
