# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangohaystack', '0003_auto_20170627_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AlterField(
            model_name='note',
            name='fileUpload',
            field=models.FileField(upload_to='fileup'),
        ),
    ]
