# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangohaystack', '0006_auto_20170628_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
