# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangohaystack', '0010_person_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='ip_address',
        ),
    ]
